export const routes = [
  "/",
  "/about",
  "/approach",
  "/approach/assessment",
  "/approach/recovery",
  "/approach/performance",
  "/contact",
  "/programs",
  "/programs/lower-back",
  "/programs/neck-shoulder",
  "/programs/knee",
  "/programs/post-surgery",
  "/programs/parkinsons",
  "/programs/athlete",
  "/programs/chronic-pain",
  "/programs/chronic-pain/lower-back",
  "/programs/chronic-pain/shoulder",
  "/programs/chronic-pain/elbow",
  "/programs/chronic-pain/ankle",
  "/programs/neuro",
  "/programs/neuro/parkinson",
  "/programs/neuro/stroke",
] as const;
